config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

  get 'alohas/food' => 'alohas#food'
  get 'alohas/spot' => 'alohas#spot'
  get 'alohas/leisure' => 'alohas#leisure'
  get 'alohas/omiyage' => 'alohas#omiyage'
  

  resources :alohas ,only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create]
  end
  namespace :admin do
    resources :alohas, only: [:new]
  end
  
  root 'alohas#index'

end

app/models/aloha.rb
class Aloha < ApplicationRecord
    mount_uploader :photo, PhotoUploader
    has_many :comments, dependent: :destroy
    has_many :images, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :aloha
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :aloha
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/alohas_controller.rb
class Admin::AlohasController < ApplicationController
    before_action :if_not_admin
    before_action :set_aloha, only: [:new, :edit, :create]
    



    private
    def if_not_admin
        redirect_to root_path unless current_user.admin?
    end
    def set_aloha
        @aloha = Aloha.new
    end
    def aloha_params
        params.require(:aloha).permit(:name, :time, :category, :about, :price, :link, :parking, :point, :photo, :address, :phonenumber)
    end
end

app/controllers/alohas_controller.rb
class AlohasController < ApplicationController
        before_action :authenticate_user!, only: [:new, :create]
          def new
            @aloha = Aloha.new
          end
        
          def create
            aloha = Aloha.new(aloha_params)
            aloha.user_id = current_user.id
    
            if aloha.save
              p params[:aloha][:images]
              params[:aloha][:images]&.each do |image|
                  p image
                  Image.create!(image: image, aloha_id: aloha.id)
              end
    
              if aloha.category == 'グルメ'
                redirect_url = '/alohas/food'
              elsif aloha.category == 'スポット'
                redirect_url = '/alohas/spot'
              elsif aloha.category =='お土産'
                redirect_url = '/alohas/omiyage'
              else
                redirect_url = '/alohas/leisure'
              end
    
            else
              redirect_url = '/alohas/new'
    
            end
            redirect_to redirect_url
        end
            
    
          def show
            @aloha = Aloha.find(params[:id])
            @comments = @aloha.comments
            @comment = Comment.new
            @rank = @aloha.comments.average(:star)
          end
    
          def edit
            @aloha = Aloha.find(params[:id])
          end
    
          def update
            aloha = Aloha.find(params[:id])
            if aloha.update(aloha_params)
              redirect_to :action => "show", :id => aloha.id
            else
              redirect_to :action => "new"
            end
          end
    
          def destroy
            aloha = Aloha.find(params[:id])
    
            if aloha.category == 'グルメ'
              redirect_url = '/alohas/food'
            elsif aloha.category == 'スポット'
              redirect_url = '/alohas/spot'
            elsif aloha.category =='お土産'
              redirect_url = '/alohas/omiyage'
            else
              redirect_url = '/alohas/leisure'
            end
            
            aloha.destroy
            redirect_to redirect_url
    
    end
    
          def food
            @alohas = Aloha.all
            @ranked_posts = Aloha
            .left_joins(:comments)
            .select("alohas.*, COALESCE(AVG(CAST(comments.star AS DECIMAL)), 0) as average_star")
            .group("alohas.id")
            .where(category: "グルメ")
            .order("average_star DESC")
            .limit(5)
          end
    
          def spot
            @alohas = Aloha.all
            @ranked_posts = Aloha
            .left_joins(:comments)
            .select("alohas.*, COALESCE(AVG(CAST(comments.star AS DECIMAL)), 0) as average_star")
            .group("alohas.id")
            .where(category: "スポット")
            .order("average_star DESC")
            .limit(5)
          
    end
    
          def leisure
            @alohas = Aloha.all
            @ranked_posts = Aloha
            .left_joins(:comments)
            .select("alohas.*, COALESCE(AVG(CAST(comments.star AS DECIMAL)), 0) as average_star")
            .group("alohas.id")
            .where(category: "レジャー")
            .order("average_star DESC")
            .limit(5)
    end
    
          def omiyage
            @alohas = Aloha.all
            @ranked_posts = Aloha
            .left_joins(:comments)
            .select("alohas.*, COALESCE(AVG(CAST(comments.star AS DECIMAL)), 0) as average_star")
            .group("alohas.id")
            .where(category: "お土産")
            .order("average_star DESC")
            .limit(5)
    end
    
          private
          def aloha_params
            params.require(:aloha).permit(:name, :time, :category, :about, :price, :link, :parking, :point, :photo, :image, :lat, :lng, :address, :phonenumber)
          end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      aloha = Aloha.find(params[:aloha_id])
      comment = aloha.comments.build(comment_params)
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) 
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) 
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content, :star)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin/alohas_helper.rb
module Admin::AlohasHelper
end

app/helpers/alohas_helper.rb
module AlohasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/alohas/food.html.erb
<!DOCTYPE html>
<html lang="ja">
 <head>
   <meta charset="UTF-8">
   <title>グルメランキング</title>
   <link rel="stylesheet" type="text/css" href="food.css">
   <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
</head>

<div class="first-block-food">
  <div class="title">
    <h1>グルメランキング</h1>
  </div>
</div>






<div class="second-block-food">
  <% counter = 0 %>
  <% @ranked_posts.each do |aloha| %>
  <div class="フードランキング">   
    <div class="写真">
      <div class='順位'>   
        <% counter += 1 %>
        <!-- ここで counter 変数を使用して処理を行います -->
        <p><%= counter %></p>
      </div>
      <%= image_tag aloha.photo_url, size: "400x300" if aloha.photo? %>

    </div>

    <div class="内容">
      <div class="名前">
        <%= link_to aloha_path(aloha.id) do %>
          <li><%= aloha.name %></li>
        <% end %>
      </div>

      <div class="星数字">
        <span class="star-rating">
          <span class="star-rating-front" style="width: <%= getPercent(aloha.average_star) %>%;">★★★★★</span>
          <span class="star-rating-back">★★★★★</span>
        </span> 
        <%= aloha.average_star %>
      </div>

      <div class="ポイント">
        <%= aloha.about %>
      </div>

      <div class="星数字2">
        <% if user_signed_in? %> 
          <% if current_user.admin? %>
            <li>
              <%= link_to "編集する", edit_aloha_path(aloha.id) %>
              <%= button_to "削除する", aloha_path(aloha.id), method: :delete %>
            </li>
          <% end %> 
        <% end %> 
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/alohas/index.html.erb
<!DOCTYPE html>
<html lang="ja">
 <head>
   <meta charset="UTF-8">
   <title>HAWAIIの歩き方</title>
   <link rel="stylesheet" type="text/css" href="index.css">
   <link rel="preconnect" href="https://fonts.googleapis.com" />
   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
   <link href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&family=Mochiy+Pop+P+One&family=Reenie+Beanie&display=swap"
   rel="stylesheet"/>
 </head>

 <body>
   <div class="first-block">
     
     <h1 class="title">HAWAII</h1>
    
   </div>

   <div class="概要">
    <div class="文">
     <p>HAWAIIの歩き方は、<br>
      ハワイ旅行を計画しているすべてのトラベラーに向けた<br>
      観光情報サイトです。</p>
     <p>このサイトを閲覧する多くの人が<br>
      貴重なハワイ旅行を後悔せずに済むことを<br>
      目指しています。</p>
     <p>ぜひ、卒業旅行やハネムーン等でハワイに行く際には<br>
      参考にしてみてください。</p>
    </div>
   </div>



 <div class="second-block">
  <h1 class="title">ハワイ旅行POINT</h1>
   <div class="ポイント">
    <div class="文">
     <p>★料理は必ずシェアorハーフサイズにする!</p>
     <p>★レストランに行くときは上着を持っていく!</p>
     <p>★チップ文化を知っておこう！</p>
     <p>★JCBカードを持っていたら持っていこう!<br>
        →トロリーバスが無料に！！</p>
     <p>★お冷やパンでも料金を取られることあり!</p>
     <p>★アルコールを買うときはパスポートが必要!</p>
     <p>★お店の入れ替わりが激しいから最新の情報を得よう!</p>
    </div>
   </div>
 </div>

<div class="third-block">
 <h1 class="rank">ランキング</h1>
 <div class="link">
  <div class="gurume">
<%= link_to alohas_food_path do %>
 <%= image_tag 'gurume1.jpg', width: '250px', height: '250px' %>
<% end %>
  </div>

  <div class="spot">
<%= link_to alohas_spot_path do %>
 <%= image_tag 'spot1.jpg', width: '250px', height: '250px' %>
<% end %>
  </div>


  <div class="leisure">
<%= link_to alohas_leisure_path do %>
 <%= image_tag 'leisure1.jpg', width: '250px', height: '250px' %>
<% end %>
  </div>

  <div class="omiyage">
<%= link_to alohas_omiyage_path do %>
 <%= image_tag 'omiyage1.jpg', width: '250px', height: '250px' %>
<% end %>
  </div>
 </div>
</div>

<div class="fourth-block">
 <div class="map">
 </div>
</div>


 </body>
</html>
 

<style>
@import url('https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Noto+Sans+JP:wght@100&display=swap');
</style>

app/views/alohas/leisure.html.erb
<!DOCTYPE html>
<html lang="ja">
 <head>
   <meta charset="UTF-8">
   <title>レジャーランキング</title>
   <link rel="stylesheet" type="text/css" href="leisure.css">
   <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
   </head>

<div class="first-block-leisure">
 <div class="title">
  <h1>レジャーランキング</h1>
 </div>
</div>


<div class="second-block-food">
<% counter = 0 %>
<% @ranked_posts.each do |aloha| %>
<div class="フードランキング">   
  <div class="写真">
    <div class='順位'>   
      <% counter += 1 %>
      <!-- ここで counter 変数を使用して処理を行います -->
      <p><%= counter %></p>
    </div>
    <%= image_tag aloha.photo_url, size: "400x300" if aloha.photo? %>

  </div>

   <div class="内容">
    <div class="名前">
    <%= link_to aloha_path(aloha.id) do %>
      <li><%= aloha.name %></li>
    <% end %>
    </div>

    <div class="星数字">
    <span class="star-rating">
     <span class="star-rating-front" style="width: <%= getPercent(aloha.average_star) %>%;">★★★★★</span>
     <span class="star-rating-back">★★★★★</span>
     </span> 
     <%= aloha.average_star %>
    </div>

    <div class="ポイント">
     <%= aloha.about %>
    </div>

    <div class="星数字2">
 <% if user_signed_in? %> 
    <% if current_user.admin? %>
    <li>
     <%= link_to "編集する", edit_aloha_path(aloha.id) %>
     <%= button_to "削除する", aloha_path(aloha.id), method: :delete %>
    </li>
     <% end %> 
    <% end %> 
   </div>
  </div>
   
  </div>
  <% end %>
</div>

<style>
@import url('https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Noto+Sans+JP:wght@100&display=swap');
</style>

app/views/alohas/omiyage.html.erb
<!DOCTYPE html>
<html lang="ja">
 <head>
   <meta charset="UTF-8">
   <title>お土産ランキング</title>
   <link rel="stylesheet" type="text/css" href="food.css">
   <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
   </head>

<div class="first-block-omiyage">
 <div class="title">
  <h1>お土産ランキング</h1>
 </div>
</div>


<div class="second-block-food">
<% counter = 0 %>
<% @ranked_posts.each do |aloha| %>
<div class="フードランキング">   
  <div class="写真">
    <div class='順位'>   
      <% counter += 1 %>
      <!-- ここで counter 変数を使用して処理を行います -->
      <p><%= counter %></p>
    </div>
    <%= image_tag aloha.photo_url, size: "400x300" if aloha.photo? %>

  </div>

   <div class="内容">
    <div class="名前">
    <%= link_to aloha_path(aloha.id) do %>
      <li><%= aloha.name %></li>
    <% end %>
    </div>

    <div class="星数字">
    <span class="star-rating">
     <span class="star-rating-front" style="width: <%= getPercent(aloha.average_star) %>%;">★★★★★</span>
     <span class="star-rating-back">★★★★★</span>
     </span> 
     <%= aloha.average_star %>
    </div>

    <div class="ポイント">
     <%= aloha.about %>
    </div>

    <div class="星数字2">
    <% if user_signed_in? %> 
       <% if current_user.admin? %>
       <li>
        <%= link_to "編集する", edit_aloha_path(aloha.id) %>
        <%= button_to "削除する", aloha_path(aloha.id), method: :delete %>
       </li>
        <% end %> 
       <% end %> 
      </div>
     </div>
      
     </div>
     <% end %>
   </div>

<style>
@import url('https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Noto+Sans+JP:wght@100&display=swap');
</style>

app/views/alohas/show.html.erb
<!DOCTYPE html>
<html lang="ja">
 <head>
   <meta charset="UTF-8">
   <title>詳細</title>
   <%= stylesheet_link_tag "show" %>
   <link href="https://fonts.googleapis.com/css?family=Bowlby+One" rel="stylesheet">
 </head>


 <div class="first-block-show">

  <div class="name">
   <div class="title">
    <h1><p><%= @aloha.name %></p></h1>
   </div>
  </div>

  <div class="photo">
    <% @aloha.images.each do |image| %>
      <%= image_tag image.image_url, size: "350x300" %>
    <% end %>
  </div>
 </div>

 <div class="second-block-show">
  <div class="内容">
   <div class="タイトル箱">
   <div class="タイトル">
    information
   </div>
   </div>
   <div class="文">
    <ul>
    <li>おすすめ度
      <div class="おすすめ度">
        <%= @rank %>
      </div>
    </li>

    <li>営業時間
      <div class="営業時間">
        <%= @aloha.time %>
      </div>
    </li>

    <li>おすすめポイント
      <div class="おすすめポイント">
        <%= @aloha.about %>
      </div>
    </li>

    <li>予算
      <div class="予算">
        <%= @aloha.price %>
      </div>
    </li>

    <li>公式ホームページ
      <div class="ホームページ">
        <%= @aloha.link %>
      </div>
    </li>

    <li>駐車場
      <div class="駐車場">
        <%= @aloha.parking %>
      </div>
    </li>

    <li>注意点
      <div class="注意点">
        <%= @aloha.point %>
      </div>
    </li>

    <li>住所
      <div class="住所">
        <%= @aloha.address %>
      </div>
    </li>

    <li>電話番号
      <div class="電話番号">
        <%= @aloha.phonenumber %>
      </div>
    </li>

    </ul>
   </div>


   <div class="googlemap">
    <div class="所在地">
      所在地
    </div>
      <div id='map'></div>

<style>
#map {
  height: 500px;
  width: 60%;
}
</style>
  </div>

<!-- js部分 -->
<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: <%= @aloha.lat %>, lng: <%= @aloha.lng %>},
    zoom: 15,
  });

   marker = new google.maps.Marker({
    position:  {lat: <%= @aloha.lat %>, lng: <%= @aloha.lng %>},
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCnAUAjQ8vPm_rM1aR5Q81Ah6G2ivYL5oI&callback=initMap" async defer></script>
   </div>
 </div>

<div class="comment-wrapper">
<h3>comment</h3>
<div class="comment-box">
  <% @comments.each do |c| %>
    <div class="コメント">
      <div class="main-box">
        <div class="left-container"><%= c.content %></div>
        <div class="right-container">
         <span class="star-rating">
          <span class="star-rating-front" style="width: <%= getPercent(c.star.to_i) %>%;">★★★★★</span>
          <span class="star-rating-back">★★★★★</span>
         </span> 
        </div>
      </div>
      <% end %>
    </div>
</div>
</div>
</div>



<div class="comment-create">
  <div class="comment-create-box">
   <div class="post">
    comment post
   </div>
   <div class="love">
    <h5 class="コメント入力">コメント入力</h5>
    <div class="テキストエリア">
     <%= form_with(model: [@aloha, @comment], local: true) do |f| %>
     <%= f.text_area :content %>
    </div>

    <h5>総合評価</h5>
    <div class="post_form">
    <%= f.radio_button :star, 5 ,id: 'star1'%>
    <label for="star1"><span class="text">最高</span>★</label>

    <%= f.radio_button :star, 4 ,id: 'star2'%>
    <label for="star2"><span class="text">良い</span>★</label>

    <%= f.radio_button :star, 3 ,id: 'star3'%>
    <label for="star3"><span class="text">普通</span>★</label>

    <%= f.radio_button :star, 2 ,id: 'star4'%>
    <label for="star4"><span class="text">悪い</span>★</label>

    <%= f.radio_button :star, 1 ,id: 'star5'%>
    <label for="star5"><span class="text">最悪</span>★</label>
    </div>
    <div class="コメントする">
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
    </div>
   </div>
  </div>
</div>


</div>


<div class="リンクリンク">
<%= link_to "HOMEに戻る", alohas_path %>

<% if user_signed_in? %> 
<% if current_user.admin? %>
  <%= link_to "編集する", edit_aloha_path(@aloha.id) %>
<% end %> 
<% end %> 


<% if @aloha.category == "グルメ" %>
  <%= link_to "ランキングに戻る", alohas_food_path %>
<% elsif @aloha.category == "スポット" %>
  <%= link_to "ランキングに戻る", alohas_spot_path %>
<% elsif @aloha.category == "レジャー" %>
  <%= link_to "ランキングに戻る", alohas_leisure_path %>
<% elsif @aloha.category == "お土産" %>
  <%= link_to "ランキングに戻る", alohas_omiyage_path %>
<% end %>
</div>

<style>
@import url('https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Noto+Sans+JP:wght@100&display=swap');
</style>

app/views/alohas/spot.html.erb
<!DOCTYPE html>
<html lang="ja">
 <head>
   <meta charset="UTF-8">
   <title>スポットランキング</title>
   <link rel="stylesheet" type="text/css" href="spot.css">
   <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
   </head>

<div class="first-block-spot">
 <div class="title">
  <h1>スポットランキング</h1>
 </div>
</div>


<div class="second-block-food">
<% counter = 0 %>
<% @ranked_posts.each do |aloha| %>
<div class="フードランキング">   
  <div class="写真">
    <div class='順位'>   
      <% counter += 1 %>
      <!-- ここで counter 変数を使用して処理を行います -->
      <p><%= counter %></p>
    </div>
    <%= image_tag aloha.photo_url, size: "400x300" if aloha.photo? %>

  </div>

   <div class="内容">
    <div class="名前">
    <%= link_to aloha_path(aloha.id) do %>
      <li><%= aloha.name %></li>
    <% end %>
    </div>

    <div class="星数字">
    <span class="star-rating">
     <span class="star-rating-front" style="width: <%= getPercent(aloha.average_star) %>%;">★★★★★</span>
     <span class="star-rating-back">★★★★★</span>
     </span> 
     <%= aloha.average_star %>
    </div>

    <div class="ポイント">
     <%= aloha.about %>
    </div>
   
    <div class="星数字2">
    <% if user_signed_in? %> 
       <% if current_user.admin? %>
       <li>
        <%= link_to "編集する", edit_aloha_path(aloha.id) %>
        <%= button_to "削除する", aloha_path(aloha.id), method: :delete %>
       </li>
        <% end %> 
       <% end %> 
      </div>
     </div>
      
     </div>
     <% end %>
   </div>

<style>
@import url('https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Noto+Sans+JP:wght@100&display=swap');
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hawaiiiii</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
   <header>
    <div class="header-list">
     <ul>
      <% if user_signed_in? %> 
      <% if current_user.admin? %>
       <li><%= link_to "新規投稿", new_admin_aloha_path %></li>
      <% end %> 
       
       <li><%= link_to "HOME", alohas_path %></li>
      <li><%= button_to 'LOGOUT', destroy_user_session_path, method: :delete %></li>
    
       <% else %>
       <li><%= link_to "HOME", alohas_path %></li>
       <li><%= link_to "SIGNUP", new_user_registration_path %></li>
       <li><%= link_to "LOGIN", new_user_session_path %></li>
      <% end %>
     </ul>
    </div>
   </header>
   <main>
    <%= yield %>
   </main>
  </body>

</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>